name: Main Docker Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker_build_push:
    uses: ./.github/workflows/reusedepoly.yml  # Use correct path and avoid trailing gibberish
    with:
      image_name: 'bookmymovie'
      dockerhub_username: 'pandusa2003'
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}  # Correct secret reference
