name: Reusable Docker Build and Push

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      dockerhub_username:
        required: true
        type: string
      dotnet_version:
        required: false
        type: string
        default: '8.0'
    secrets:
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the application
        run: dotnet build --configuration Release --no-restore
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ inputs.dockerhub_username }}/${{ inputs.image_name }}:latest .
          docker tag ${{ inputs.dockerhub_username }}/${{ inputs.image_name }}:latest ${{ inputs.dockerhub_username }}/${{ inputs.image_name }}:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ${{ inputs.dockerhub_username }}/${{ inputs.image_name }}:latest
          docker push ${{ inputs.dockerhub_username }}/${{ inputs.image_name }}:${{ github.sha }}
